site_name: Meraki

nav:
  - Inicial: index.md
  - Planejamento:
    - Planejamento Inicial: planejamento.md
    - Planejamento de Melhorias: melhorias.md
  - Contexto de Uso:
    - Storyboard: storyboard.md
    - Análise de Usuário: analise_do_usuario.md
        # - Personas: personas.md
    - Análise de Tarefas:
        - HTA: hta.md
        - GOMS: goms.md
    - Análise do Uso:
        - Avaliação heurística: avaliacao_heuristica.md
        - Características da Plataforma: caracteristicas.md
    - Técnicas de Análise:
        - Entrevistas: entrevistas/entrevistas.md
        - Questionário: questionario.md
  - Concepção/Avaliação:
    - Planejamento da Avaliação: planejamento_avaliacao.md
    - Guia de estilo: novo_guia.md
    - Metas de usabilidade: metas_usabilidade.md
    - Protótipo de Papel: prototipo_papel.md
    - Protótipo de Média Fidelidade: media_fidelidade.md
    - Protótipo de Alta Fidelidade: alta_fidelidade.md
theme:
  name: readable
  custom_dir: custom

extra_css:
  - 'stylesheets/common.css'
