site_name: Conect.Ideas

nav:
  - Inicial: index.md
  - Planejamento: planejamento.md
  - Avaliação heurística: avaliacao_heuristica.md
  - Storyboard: storyboard.md
  - Metas de usabilidade: metas_usabilidade.md
  - Guia de estilo: estilo_guia.md
  - Entrevistas: entrevistas/entrevistas.md
  - Personas: personas.md
theme:
  name: readable
  custom_dir: custom

extra_css:
  - 'stylesheets/common.css'
