site_name: Meraki

nav:
  - Inicial: index.md
  - Planejamento: planejamento.md
  - Contexto de Uso:
    - Storyboard: storyboard.md
    - Análise de Usuário:
        - Personas: personas.md
    - Análise de Tarefas:
        - HTA: hta.md
    - Análise do Uso:
        - Avaliação heurística: avaliacao_heuristica.md
        - Características da Plataforma: caracteristicas.md
    - Técnicas de Análise:
        - Entrevistas: entrevistas/entrevistas.md
        - Questionário: questionario.md
    - Guia de estilo: estilo_guia.md
  - Concepção/Avaliação:
    - Guia de estilo: novo_guia.md
    - Metas de usabilidade: metas_usabilidade.md
    - Protótipo de Papel: prototipo_papel.md
    - Protótipo de Média Fidelidade: media_fidelidade.md
theme:
  name: readable
  custom_dir: custom

extra_css:
  - 'stylesheets/common.css'
