site_name: Meraki

nav:
  - Inicial: index.md
  - Planejamento: planejamento.md
  - Contexto de Uso:
    - Storyboard: storyboard.md
    - Análise de Usuário:
        - Personas: personas.md
    - Análise do Uso:
        - Avaliação heurística: avaliacao_heuristica.md
    - Técnicas de Análise:
        - Entrevistas: entrevistas/entrevistas.md
  - Concepção/Avaliação:
    - Metas de usabilidade: metas_usabilidade.md
    - Guia de estilo: estilo_guia.md
    - Protótipo de Papel: protótipo_papel.md
theme:
  name: readable
  custom_dir: custom

extra_css:
  - 'stylesheets/common.css'
